### ISSUE TITLE
malloc(): corrupted top size Aborted (core dumped) when using QOI.cpp

### ISSUE THREAD

**Issue by Garrett2532** [pfusik/qoi-ci#11]
Hello, 

I am getting this error when writing a main for the c++ implementation

> malloc(): corrupted top size
> Aborted (core dumped)

Using gdb I was able to determine that the error occurs on line 146 of QOI.cpp

>  std::shared_ptr<int[]> pixels = std::make_shared<int[]>(pixelsSize);

I looked into shared pointer and everything looks correct. I am unable to determine whether this is a bug with my main that I wrote or with the cpp. 

This is my main to recreate:

```
#include <iostream>
#include "QOI.hpp"
int main() {

        //Encode
            std::cout << "Encoding! \n";
            QOIEncoder encoder;     // create an instance of the encoder segmentation fault
            const int pixels[9] = {0,1,2,3,4,5,6,7,8};
            const int* firstPixel = &pixels[0];//pointer to a const int
            int width = 3;
            int height = 3;
            bool alpha = false;
            bool lineColorspace = false;

            bool encodedbool = encoder.QOIEncoder::encode(width, height, firstPixel, alpha, lineColorspace);
            const uint8_t*  data = encoder.QOIEncoder::getEncoded();
            std::cout << encodedbool << std::endl;
            std::cout << data << std::endl;


            //DECODE
            std::cout << "Decoding \n" << std::endl;
            QOIDecoder decoder;
            bool decodedbool = decoder.QOIDecoder::decode(encoder.QOIEncoder::getEncoded(), encoder.QOIEncoder::getEncodedSize());
            std::cout << decodedbool << std::endl;
            std::cout << decoder.QOIDecoder::getWidth() << std::endl;
            std::cout << decoder.QOIDecoder::getHeight() << std::endl;
            std::cout << decoder.QOIDecoder::getPixels() << std::endl;
            return 0;
}
```

The output that I get when running with this main is 

> 
> Encoding!
> 1
> qoif
> Decoding
> 
> malloc(): corrupted top size
> Aborted (core dumped)
> 

Sorry if this is a silly question I have just been on this for a while

**Comment by Garrett2532** [comment]
I did compile with C++20 my full compile command is 
`g++ -std=gnu++20 main.cpp QOI.cpp -o Encode`

I am using g++ version 10.3.0 on Ubuntu 20.04.4

**Comment by pfusik** [comment]
It looks like you need g++ 12.

g++ 11.2.0 on Ubuntu 22.04 give a compile-time error about `std::make_shared` not supported:

	fox@bu22:~/qoi-ci-2.0.0/transpiled$ uname -a
	Linux bu22 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
	fox@bu22:~/qoi-ci-2.0.0/transpiled$ g++ -v
	Using built-in specs.
	COLLECT_GCC=g++
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
	OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
	OFFLOAD_TARGET_DEFAULT=1
	Target: x86_64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
	Thread model: posix
	Supported LTO compression algorithms: zlib zstd
	gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
	fox@bu22:~/qoi-ci-2.0.0/transpiled$ g++ -std=gnu++20 main.cpp QOI.cpp -o Encode
	In file included from /usr/include/c++/11/memory:77,
					 from QOI.hpp:4,
					 from QOI.cpp:4:
	/usr/include/c++/11/bits/shared_ptr.h: In instantiation of ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = unsigned char []; _Alloc = std::allocator<unsigned char []>; _Args = {int}]’:
	/usr/include/c++/11/bits/shared_ptr.h:878:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = unsigned char []; _Args = {int}]’
	QOI.cpp:19:66:   required from here
	/usr/include/c++/11/bits/shared_ptr.h:860:21: error: static assertion failed: make_shared<T[]> not supported
	  860 |       static_assert(!is_array<_Tp>::value, "make_shared<T[]> not supported");
		  |                     ^~~~~~~~~~~~~~~~~~~~~
	/usr/include/c++/11/bits/shared_ptr.h:860:21: note: ‘!(bool)std::integral_constant<bool, true>::value’ evaluates to false
	/usr/include/c++/11/bits/shared_ptr.h: In instantiation of ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = int []; _Alloc = std::allocator<int []>; _Args = {int&}]’:
	/usr/include/c++/11/bits/shared_ptr.h:878:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = int []; _Args = {int&}]’
	QOI.cpp:146:57:   required from here
	/usr/include/c++/11/bits/shared_ptr.h:860:21: error: static assertion failed: make_shared<T[]> not supported
	/usr/include/c++/11/bits/shared_ptr.h:860:21: note: ‘!(bool)std::integral_constant<bool, true>::value’ evaluates to false

g++ 12.2.0 on Windows works fine:

	C:\0\ci\qoi\qoi-ci\transpiled>g++ -v
	Using built-in specs.
	COLLECT_GCC=g++
	COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
	Target: x86_64-w64-mingw32
	Configured with: ../gcc-12.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
	Thread model: posix
	Supported LTO compression algorithms: zlib zstd
	gcc version 12.2.0 (Rev1, Built by MSYS2 project)

	C:\0\ci\qoi\qoi-ci\transpiled>g++ -std=gnu++20 main.cpp QOI.cpp -o Encode

	C:\0\ci\qoi\qoi-ci\transpiled>Encode
	Encoding!
	1
	qoif
	Decoding

	1
	3
	3
	0x1ef613d1af0
