### ISSUE TITLE
Help using c++ qoi implementation

### ISSUE THREAD

**Issue by scottjch** [pfusik/qoi-ci#12]
Hello,

I am trying to compress bmp files with the c++ implementation of qoi.

I am trying to read a bmp image, encode it, and decode it. However, whenever I encode the image the encoded size is greater than image size.

I am using the barbara.bmp image form the standard-test-images-for-Image-Processing github (https://github.com/mohammadimtiazz/standard-test-images-for-Image-Processing) and my code is attached. The OS reports the size as 263222 and the encoded size is 319442.

My source code is below, and I was wondering if you could help me find where I am going wrong with using the encoder and decoder?

```
#include <iostream>
#include <string>
#include "QOI.hpp"
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

int main() {
        //read image
        cout << "Reading Image:\n";
        string image_path = "./barbara.bmp";
        Mat img = imread(image_path);
        cout << "  Image read: rows: " << img.rows << ", cols: " << img.cols << "\n";
        int *pixelsPtr = new int[img.rows*img.cols];
        for(int i=0; i < img.rows; i++) {
                 for(int j=0; j < img.cols; j++) {
                         Vec3b pixel = img.at<Vec3b>(i, j);
                         pixelsPtr[i+j*img.rows] = pixel[0];
                 }
        }

        //qoi_encode
        cout << "Encoding:\n";
        QOIEncoder encoder;
        int num_pixels = img.rows*img.cols;
        const int* firstPixel = pixelsPtr;
        bool alpha = false;
        bool lineColorspace = false;
        bool encodedbool = encoder.QOIEncoder::encode(img.rows, img.cols, firstPixel, alpha, lineColorspace);
        if(encodedbool){
                cout << "  Successfuly encoded!\n";
        }
        const uint8_t*  data = encoder.QOIEncoder::getEncoded();
        cout << "  encodedbool: " << encodedbool << endl;
        cout << "  encoded size: " << encoder.QOIEncoder::getEncodedSize() << endl;
		
        //qoi_decode
        cout << "Decoding:\n";
        QOIDecoder decoder;
        bool decodedbool = decoder.QOIDecoder::decode(encoder.QOIEncoder::getEncoded(), encoder.QOIEncoder::getEncodedSize());
        if (decodedbool) {
                cout << "  Successfullly decoded!\n";
        }
        cout << "  decodebool: " << decodedbool << endl;
        cout << "  width: " << decoder.QOIDecoder::getWidth() << endl;
        cout << "  height: " << decoder.QOIDecoder::getHeight() << endl;
        cout << "  pixel location: " << decoder.QOIDecoder::getPixels() << endl;

        return 0;
}
```

**Comment by pfusik** [comment]
Your QOI image is rotated and in shades of blue:

![image](https://user-images.githubusercontent.com/351822/234327521-c30fd998-0de5-4740-be8b-88a4402820f1.png)

The conversion should be:

        for(int y=0; y < img.rows;y++) {
                 for(int x=0; x < img.cols; x++) {
                         Vec3b pixel = img.at<Vec3b>(y, x);
                         pixelsPtr[y*img.cols+x] = pixel[0]|pixel[1]<<8|pixel[2]<<16;
                 }
        }

and you have swapped width with height:

    bool encodedbool = encoder.encode(img.cols, img.rows, firstPixel, alpha, lineColorspace);

(this doesn't matter for this particular image since it is square).

With these fixes, the correct QOI image is 318574 bytes.
Your original image is in grayscale (8 bits per pixel), but QOI only supports RGBA (32 bits per pixel) and the compression ratio for this particular image is less than 4:1.

**Comment by scottjch** [comment]
> Your original image is in grayscale (8 bits per pixel), but QOI only supports RGBA (32 bits per pixel).

Does this mean that QOI does not work for grayscale images?

**Comment by pfusik** [comment]
BMP, PNG and JPG all have an information in their header whether the image is grayscale. If it is, they only encode the level of gray.

QOI always encodes RGB.
