### ISSUE TITLE
paint.net fails to save the .qoi image

### ISSUE THREAD

**Issue by gezawatt** [pfusik/qoi-ci#3]
I don't know if this is a problem with the extension or with paint.net itself, but I presume it's the former.

When I try to save a .qoi image in paint.net, I get an error. I attach an error log to this post.

[Error log qoi.txt](https://github.com/pfusik/qoi-ci/files/8410095/Error.log.qoi.txt)

**Comment by pfusik** [comment]
Thanks for reporting it!

I reproduce this issue with Paint.NET 4.3.10. It worked fine on Paint.NET 4.3.3.

**Comment by gezawatt** [comment]
Works great now, thank you!
