### ISSUE TITLE
XnViewMP always saves RGB 24-bit QOI images

### ISSUE THREAD

**Issue by f2d** [pfusik/qoi-ci#4]
Hi.
I installed qoi-ci-1.1.1 plugin for all supported programs.

XnViewMP, using both Save As and Batch Convert, always saves RGB 24-bit QOI images from 24/32-bit sources.
No options/settings were possible to change in saving.
No image modification actions were used in batch conversion.

Also, conversion fails from paletted 8-bit PNG images (and possibly other limited formats).
It skips such files, which may be overlooked in large batch.
User must explicitly add changing color depth to 24/32 to succeed.
I think I had this problem not only with saving QOI, not sure.
It may be XnViewMP's own bug, but worth mentioning anyway.

Paint.net and GIMP are OK with the same plugin version 1.1.1.
Saved image is always 32-bit with RGBA header mark, regardless of alpha content and without possible user choice.
Which is fine, at least being lossless and nothing to waste (unlike BMP/PNG with alpha channel).

**Comment by pfusik** [comment]
Thanks for reporting this!

The plugin has alpha save support, but it looks like XnView MP passes the bitmap as 24-bit. I'll need to discuss this with the XnView MP author.

The plugin refuses to save with palette as QOI doesn't support this. I think that XnView MP should report it to the user. Again, I'll need to report it to the author.

**Comment by f2d** [comment]
Also noticed a small thing in XnView MP's label variables.

![XnViewMP_Uncompressed_QOI](https://user-images.githubusercontent.com/4068475/170190755-c68aaed0-4b55-4e49-a5ec-21c1256eb4bd.png)

It can say if a PNG is ZIP-compressed or not, state RLE compression where possible, etc.
It also says that a JPEG is "JPEG"-compressed.

QOI should probably be "QOI"-compressed too, even if AFAIK a file entirely made of RGB(A) codes is valid, and probably a little slower to read than a BMP. Nothing about this can be said from its header though.

I don't know if plugins have any say in this or it's entirely at XnView(MP)'s discretion.

**Comment by pfusik** [comment]
Status update: forwarded to the XnView MP author back in May. Pinged him today.

**Comment by pfusik** [comment]
I received an answer that both problems:
- saving with alpha
- reporting errors for files with palette

will be resolved in an XnView MP update.
