### ISSUE TITLE
Request for more plugins: 32-bit Imagine and XnView Classic

### ISSUE THREAD

**Issue by f2d** [pfusik/qoi-ci#5]
If possible. Thanks.

**Comment by pfusik** [comment]
XnView Classic uses the same plugin mechanism as XnView MP. Do you want a 32-bit build?

I can easily build the 32-bit Imagine plugin. Do you actually run it on 32-bit Windows or is there another reason?

**Comment by f2d** [comment]
Yes to both.

I use both XnView MP and XnView Classic, which is 32-bit only.
This will help me with big collages instead of slower PNG or bigger BMP.

I use Imagine plugin for 32-bit Total Commander's built-in Lister (viewing files with F3).
It's an over 10 year old installation of some TC powerpack, where I keep piling plugins, settings and shortcuts, while postponing the update of TC core itself. Although it has some 64-bit parts, simply adding QOI.plg64 to Imagine did not work.
This is only for quick previews. I can rely on XnView MP instead.

**Comment by pfusik** [comment]
@f2d Please try out [this alpha version](http://fusik.info/piotr/qoi-ci-1.1.2-ALPHA1-win32.zip).

**Comment by f2d** [comment]
@pfusik Both are not working.

XnView Classic top menu → Info → Formats shows QOI as Read: yes, Write: no.
I can open files (same as without installing plugin), but no QOI in save dialogs.
I tried changing `*.usr` filename to `*.dll` just in case, but same result.

For example, another user-installed plugin for Imagine (WebP) works, so this is not plugin folder mistake.

**Comment by pfusik** [comment]
What Windows version did you test on?

**Comment by f2d** [comment]
Windows 10 x64.
Does it work on some other Windows version?

**Comment by pfusik** [comment]
I thought you have a 32-bit Windows. XP could be problematic, but everything from Vista on should be fine.

If it's 10 x64, that makes debugging easier for me. Hold on for updates.

**Comment by pfusik** [comment]
Please try the [second alpha](http://fusik.info/piotr/qoi-ci-1.1.2-ALPHA2-win32.zip).

**Comment by f2d** [comment]
@pfusik 
Now saving and viewing works in XnView Classic, 32-bit alpha values are also preserved on save. Thanks.

Imagine top menu (or right click when from TCmd) → "Help" → "Supported file formats" shows QOI as Read: O, Write: X, so I can view files, but no QOI in save dialogs.

**Comment by pfusik** [comment]
This is expected. I haven't implemented Save in Imagine yet. It's on my todo list. :)

**Comment by pfusik** [comment]
Please check [third alpha](http://fusik.info/piotr/qoi-ci-1.1.2-ALPHA3-win64.msi). Changes:
- Packaged the 32-bit plugins into the installer (delete the plugins you installed manually first)
- Saving in Imagine

**Comment by f2d** [comment]
XnViewMP still does not keep transparency (alpha channel), but all others seem working fine.
Saving in Imagine 32/64-bit works, from TCmd Lister or separately, from 8-bit PNGs or 32-bit with transparency too.

**Comment by pfusik** [comment]
Alpha channel is to be addressed in XnViewMP >1.0.0.
QOI doesn't support palettes and the plugin reports that to Imagine, which apparently expands the image to 24-bit so it can be saved.

I've just [released 1.1.2](https://github.com/pfusik/qoi-ci/releases/tag/qoi-ci-1.1.2). It's practically identical to the third alpha.

Thank you!
